config/routes.rb
Rails.application.routes.draw do
  # 管理者側
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:      'admins/passwords'
 }

  namespace :admin do
    get ''=> 'homes#top'
    resources :genres, only: [:index, :create, :update, :edit]
    resources :items, except: [:destroy]
    resources :orders, only: [:show, :update]
    resources :customers, only: [:index,:show,:edit,:update]
    resources :order_details, only: [:update]
 end

  # 会員側
  devise_for :customers, skip: [:registrations, :passwords],
                         controllers: {
  sessions:      'customers/sessions',
  registrations: 'customers/registrations'
 }
  devise_scope :customer do
    get 'customers/sign_up' => 'customers/registrations#new', as: :new_customer_registration
    post 'customers' => 'customers/registrations#create', as: :customer_registration
  end

  scope module: :public do
    resource :customers, only: [:edit, :update]
    get "customers/my_page" => "customers#show"
    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "customers/change" => "customers#change"

    root to: 'homes#top'
    get 'about' => "homes#about"

    post 'orders/confirm'
    get 'orders/thanks'
    resources :orders, only: [:new, :create, :index, :show]

    resources :items, only: [:index, :show]

    delete 'cart_items/destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]

    resources :addresses, only: [:index, :create, :edit, :update, :destroy]

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  attachment :image

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true,
                    numericality: { only_integer: true}

  def add_tax_price
    (self.price * 1.10).round
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.page(params[:page]).per(5)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice]="新しい商品を登録しました"
      redirect_to admin_item_path(@item.id)
    else
      flash.now[:notice]="各項目に情報を入力してください"
      render "new"
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice]="商品情報を更新しました"
      redirect_to admin_item_path(@item.id)
    else
      flash.now[:notice]="各項目に情報を入力してください"
      render "edit"
    end
  end

  private
  def item_params
    params.require(:item).permit(:genre_id,:name,:image,:introduction,:price,:is_active)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/_error_msg.html.erb
<% if item.errors.any? %>
  <div id="error_explanation">
    <h3>入力必須項目が<%= pluralize(item.errors.count, "件") %> あります</h3>
    <ul>
      <% item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/items/_item_form.html.erb
  <div class="row mb-3 form-group">

    <div class="col-md-4">
      <%= f.label(:image, "商品画像") %>
    </div>
    <div class="col-md-8">
      <%= f.attachment_field :image, class:"form-control-file" %>
    </div>
  </div>
  <div class="row mb-3 form-group">
    <div class="col-md-4">
      <%= f.label(:name, "商品名") %>
    </div>
    <div class="col-md-8">
      <%= f.text_field :name, class:"form-control", placeholder:"商品名" %>
    </div>
  </div>
  <div class="row mb-3 form-group">
    <div class="col-md-4">
      <%= f.label(:introduction, "商品説明") %>
    </div>
    <div class="col-md-8">
      <%= f.text_area :introduction, rows:"6", class:"form-control", placeholder:"ここに説明文を記述します" %>
    </div>
  </div>
  <div class="row mb-3 form-select">
    <div class="col-md-4">
      <%= f.label(:genre_id, "ジャンル") %>
    </div>
    <div class="col-md-8 ">
      <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank:"--選択してください--" %>
    </div>
  </div>
  <div class="row mb-3 form-group">
    <div class="col-md-4">
      <%= f.label(:price, "税抜価格") %>
    </div>
    <div class="col-md-8 d-flex flex-row">
      <%= f.text_field :price, class:"form-control", placeholder:"1000" %><span>円</span>
    </div>
  </div>
  <div class="row mb-3 form-group">
    <div class="col-md-4">
      <%= f.label(:is_active, "販売ステータス") %>
    </div>
    <div class="col-md-8">
      <div class="radio-inline">
        <%= f.radio_button :is_active, "true" %>
        <%= f.label :is_active, "販売中", class: "mr-3" %>

        <%= f.radio_button :is_active, "false" %>
        <%= f.label :is_active, "販売停止中" %>
      </div>
    </div>
  </div>
  <% if local_assigns[:edit_flag].present? %>
    <div class="form-group">
      <div class="col-md-offset-4 col-md-8">
        <%= f.submit "変更を保存", class:"btn btn-success" %>
      </div>
    </div>
  <% else %>
    <div class="form-group">
      <div class="col-md-offset-4 col-md-8">
        <%= f.submit "新規登録", class:"btn btn-success" %>
      </div>
    </div>
  <% end %>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class=" mx-auto">
      <!--エラー文-->
      <%= render "admin/items/error_msg", item: @item%>

      <%= form_with model:@item, url:admin_item_path, local:true do |f| %>
        <%= render :partial => 'item_form', :locals => {:f => f, :edit_flag => true} %>
      <% end%>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 mx-auto mb-3 d-flex">
      <h4>商品一覧</h4>
      <%= link_to new_admin_item_path, class: "text-dark fa-2x fa-pull-right ml-auto" do %>
        <i class="fas fa-plus"></i>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-10 mx-auto">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td><%= link_to item.name, admin_item_path(item.id) %></td>
            <td><%= item.price.to_s(:delimited) %></td>
            <td><%= item.genre.name %></td>
            <td class="text-success font-weight-bold"><%= item.is_active ? '販売' : '販売停止中' %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="d-flex justify-content-center">
        <%= paginate @items %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <!--エラー文-->
      <%= render "admin/items/error_msg", item: @item%>

      <%= form_with model:@item, url:admin_items_path, local:true do |f| %>
        <%= render :partial => 'item_form', :locals => {:f => f} %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <%= attachment_image_tag @item, :image, size:"300x200", format: 'jpeg', fallback: "no_image_clock.jpg" %>
    </div>

    <div class="col-md-7">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td class="col-md-4">商品名</td>
            <td><%= @item.name %></td>
          </tr>
          <tr>
            <td>商品説明</td>
            <td><%= @item.introduction %></td>
          </tr>
          <tr>
            <td>ジャンル</td>
            <td><%= @item.genre.name %></td>
          </tr>
          <tr>
            <td>税込価格</br>（税抜価格）</td>
            <td class="align-middle"><%= @item.price.to_s(:delimited) %>(<%= @item.add_tax_price.to_s(:delimited) %>)<span>円</span></td>
          </tr>
          <tr>
            <td>販売ステータス</td>
            <td class="text-success font-weight-bold"><%= @item.is_active ? '販売' : '販売停止中' %></td>
          </tr>
        </tbody>
      </table>
      <div class="offset-md-4">
        <%= link_to "編集する", edit_admin_item_path(@item), class:"btn btn-lg btn-success px-4" %>
      </div>
    </div>
  </div>
</div>