config/routes.rb
Rails.application.routes.draw do
  # 管理者側
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:      'admins/passwords'
 }

  namespace :admin do
    get ''=> 'homes#top'
    resources :genres, only: [:index, :create, :update, :edit]
    resources :items, except: [:destroy]
    resources :orders, only: [:show, :update]
    resources :customers, only: [:index,:show,:edit,:update]
    resources :order_details, only: [:update]
 end

  # 会員側
  devise_for :customers, skip: [:registrations, :passwords],
                         controllers: {
  sessions:      'customers/sessions',
  registrations: 'customers/registrations'
 }
  devise_scope :customer do
    get 'customers/sign_up' => 'customers/registrations#new', as: :new_customer_registration
    post 'customers' => 'customers/registrations#create', as: :customer_registration
  end

  scope module: :public do
    resource :customers, only: [:edit, :update]
    get "customers/my_page" => "customers#show"
    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "customers/change" => "customers#change"

    root to: 'homes#top'
    get 'about' => "homes#about"

    post 'orders/confirm'
    get 'orders/thanks'
    resources :orders, only: [:new, :create, :index, :show]

    resources :items, only: [:index, :show]

    delete 'cart_items/destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]

    resources :addresses, only: [:index, :create, :edit, :update, :destroy]

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, numericality: { only_integer: true}
  validates :address, presence: true
  validates :telephone_number, numericality: { only_integer: true}

  def full_name
    self.last_name + " " + self.first_name
  end

  def full_name_kana
    self.last_name_kana + ' ' + self.first_name_kana
  end
  
  def full_address
    '〒' + postal_code + ' ' + address
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice]="編集に成功しました"
      redirect_to admin_customer_path(@customer)
    else
      flash.now[:notice]="編集に失敗しました"
      render "edit"
    end
  end
  
  private
  def customer_params
    params.require(:customer).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number,:is_active,:email)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    flash[:notice] = "会員登録に成功しました"
    customers_my_page_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  before_action :reject_customer, only: [:create]
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected
  
  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email])
    if @customer
      if @customer.valid_password?(params[:customer][:password]) && !@customer.is_active
      flash[:notice]="このアカウントは退会済みです"
      redirect_to new_customer_session_path
      end
    else
      flash[:notice]="必要事項を入力してください"
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/_error_msg.html.erb
<% if customer.errors.any? %>
  <div id="error_explanation">
    <h3>入力必須項目が<%= pluralize(customer.errors.count, "件") %> あります</h3>
    <ul>
      <% customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/customers/edit.html.erb
<div class="container">
    <!--エラー文-->
    <%= render "admin/customers/error_msg", customer: @customer%>
    
  <%= form_with model: @customer, url: admin_customer_path, local: true  do |f| %>
    <div class="form-group row">
      <label class="col-md-3">会員ID</label>
      <div class="col-md-3">
        <%= @customer.id %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-md-3">氏名</label>
      <div class="col-md-3">
        <%= f.text_field :last_name, autofocus: true, class: "form-control" %>
      </div>
      <div class="col-md-3">
        <%= f.text_field :first_name, autofocus: true, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-md-3">フリガナ</label>
      <div class="col-md-3">
        <%= f.text_field :last_name_kana, autofocus: true, class: "form-control" %>
      </div>
      <div class="col-md-3">
        <%= f.text_field :first_name_kana, autofocus: true, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-md-3">
        <%= f.label :postal_code, "郵便番号(ハイフンなし)" %>
      </div>
      <div class="col-md-3">
        <%= f.text_field :postal_code, autofocus: true, autocomplete: "true", class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-md-3">
        <%= f.label :address, "住所" %>
      </div>
      <div class="col-md-7">
        <%= f.text_field :address, autofocus: true, autocomplete: "true", class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-md-3">
        <%= f.label :telephone_number, "電話番号" %>
      </div>
      <div class="col-md-3">
        <%= f.text_field :telephone_number, autofocus: true, autocomplete: "true", class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-md-3">
        <%= f.label :email, "メールアドレス" %>
      </div>
      <div class="col-md-3">
        <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
      </div>
    </div>

    <div class="mb-3 form-group row">
      <div class="col-md-3">
        <%= f.label(:is_active, "会員ステータス") %>
      </div>
      <div class="col-md-8">
        <div class="radio-inline">
          <%= f.radio_button :is_active, "true" %>
          <%= f.label :is_active, "有効", class: "mr-3" %>

          <%= f.radio_button :is_active, "false" %>
          <%= f.label :is_active, "退会" %>
        </div>
      </div>
    </div>

    <div class="actions row">
      <div class="col-md-3 offset-md-3">
        <%= f.submit "変更を保存", class:"btn btn-lg btn-success px-4" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 mx-auto">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td><%= link_to customer.full_name, admin_customer_path(customer.id) %></td>
            <td><%= customer.email %></td>
            <td class="text-success font-weight-bold"><%= customer.is_active ? '有効' : '退会'  %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row mb-3">
    <h4><%= @customer.full_name %>さんの会員詳細</h4>
  </div>
  <div class="row">
    <div class="col-md-10">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td class="col-md-3">会員ID</td>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <td>氏名</td>
            <td><%= @customer.full_name %></td>
          </tr>
          <tr>
            <td>フリガナ</td>
            <td><%= @customer.full_name_kana %></td>
          </tr>
          <tr>
            <td>郵便番号</td>
            <td><%= @customer.postal_code %></td>
          </tr>
          <tr>
            <td>住所</td>
            <td><%= @customer.address %></td>
          </tr>
          <tr>
            <td>電話番号</td>
            <td><%= @customer.telephone_number %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td><%= @customer.email %></td>
          </tr>
          <tr>
            <td>会員ステータス</td>
            <td class="text-success font-weight-bold"><%= @customer.is_active ? '有効' : '退会' %></td>
          </tr>
        </tbody>
      </table>
      <div class="offset-md-3 btn-group">
        <%= link_to "編集する", edit_admin_customer_path(@customer), class:"btn btn-success px-3" %>
      </div>
      <div class="offset-md-1 btn-group">
        <%= link_to "注文履歴一覧を見る", admin_path, class:"btn btn-primary px-3" %>
      </div>
    </div>
  </div>
</div>