config/routes.rb
Rails.application.routes.draw do
  # 管理者側
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:      'admins/passwords'
 }

  namespace :admin do
    get ''=> 'homes#top'
    resources :genres, only: [:index, :create, :update, :edit]
    resources :items, except: [:destroy]
    resources :orders, only: [:show, :update]
    resources :customers, only: [:index,:show,:edit,:update]
    resources :order_details, only: [:update]
 end

  # 会員側
  devise_for :customers, skip: [:registrations, :passwords],
                         controllers: {
  sessions:      'customers/sessions',
  registrations: 'customers/registrations'
 }
  devise_scope :customer do
    get 'customers/sign_up' => 'customers/registrations#new', as: :new_customer_registration
    post 'customers' => 'customers/registrations#create', as: :customer_registration
  end

  scope module: :public do
    resource :customers, only: [:edit, :update]
    get "customers/my_page" => "customers#show"
    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "customers/change" => "customers#change"

    root to: 'homes#top'
    get 'about' => "homes#about"

    post 'orders/confirm'
    get 'orders/thanks'
    resources :orders, only: [:new, :create, :index, :show]

    resources :items, only: [:index, :show]

    delete 'cart_items/destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]

    resources :addresses, only: [:index, :create, :edit, :update, :destroy]

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: { 入金待ち: 0,  入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }

  validates :payment_method, presence: true
  validates :total_payment, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true
  validates :name, presence: true

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def show
    @order = Order.find(params[:id])
    @sum = 0
    @order.order_details.each do |order_detail|
      @sum += order_detail.amount * order_detail.price
    end
  end

  def update
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row mb-3">
    <h4>注文履歴詳細</h4>
  </div>
  <div class="row mb-3">
    <div>
      <table class="table table-condensed table-borderless">
        <tbody>
          <tr>
            <th>購入者</th>
            <td><%= link_to @order.customer.full_name, admin_customer_path(@order.customer_id) %></td>
          </tr>
          <tr>
            <th>注文日</th>
            <td><%= l @order.created_at %></td>
          </tr>
          <tr>
            <th class="d-flex align-items-start">配送先</th>
            <td>
              〒<%= @order.postal_code %>
              <%= @order.address %></br>
              <%= @order.name %>
            </td>
          </tr>
          <tr>
            <th>支払方法</th>
            <td><%= @order.payment_method_i18n %></td>
          </tr>
          <!--<tr>-->
          <!--  <th>注文ステータス</th>-->
          <!--  <td></td>-->
          <!--</tr>-->
        </tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <table class="table table-borderless">
        <thead class="thead-light">
          <tr>
            <th>商品名</th>
            <th class="col-md-3">単価（税込）</th>
            <th class="col-md-2">数量</th>
            <th class="col-md-2">小計</th>
            <!--<th>製作ステータス</th>-->
            <!--<th colspan="2"></th>-->
          </tr>
        </thead>
        <tbody>
          <% @order.order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= order_detail.price.to_s(:delimited) %></td>
            <td><%= order_detail.amount %></td>
            <td>
              <% @total = order_detail.price * order_detail.amount %>
              <%= @total.to_s(:delimited) %>
            </td>
            <!--<td></td>-->
            <!--<td></td>-->
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-md-3 d-flex align-items-end">
      <table class="table table-condensed table-borderless">
        <tr>
          <th>商品合計</th>
          <td><%= @sum.to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <th>送料</th>
          <td><%= @order.delivery_fee %>円</td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <td><%= @order.total_payment.to_s(:delimited) %>円</td>
        </tr>
      </table>
    </div>
  </div>
</div>