config/routes.rb
Rails.application.routes.draw do
  # 管理者側
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:      'admins/passwords'
 }

  namespace :admin do
    get ''=> 'homes#top'
    resources :genres, only: [:index, :create, :update, :edit]
    resources :items, except: [:destroy]
    resources :orders, only: [:show, :update]
    resources :customers, only: [:index,:show,:edit,:update]
    resources :order_details, only: [:update]
 end

  # 会員側
  devise_for :customers, skip: [:registrations, :passwords],
                         controllers: {
  sessions:      'customers/sessions',
  registrations: 'customers/registrations'
 }
  devise_scope :customer do
    get 'customers/sign_up' => 'customers/registrations#new', as: :new_customer_registration
    post 'customers' => 'customers/registrations#create', as: :customer_registration
  end

  scope module: :public do
    resource :customers, only: [:edit, :update]
    get "customers/my_page" => "customers#show"
    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "customers/change" => "customers#change"

    root to: 'homes#top'
    get 'about' => "homes#about"

    post 'orders/confirm'
    get 'orders/thanks'
    resources :orders, only: [:new, :create, :index, :show]

    resources :items, only: [:index, :show]

    delete 'cart_items/destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]

    resources :addresses, only: [:index, :create, :edit, :update, :destroy]

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true

  def subtotal
    item.add_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, numericality: { only_integer: true}
  validates :address, presence: true
  validates :telephone_number, numericality: { only_integer: true}

  def full_name
    self.last_name + " " + self.first_name
  end

  def full_name_kana
    self.last_name_kana + ' ' + self.first_name_kana
  end
  
  def full_address
    '〒' + postal_code + ' ' + address
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  validates :name, presence: true
  
  def self.serch(serch)
    if serch
      Genre.where(['name LIKE ?', "%#{serch}%"])
    else
      Genre.all
    end
  end

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  attachment :image

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true,
                    numericality: { only_integer: true}

  def add_tax_price
    (self.price * 1.10).round
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: { 入金待ち: 0,  入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }

  validates :payment_method, presence: true
  validates :total_payment, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true
  validates :name, presence: true

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    genre = Genre.new(genre_params)
    if genre.save
      flash[:notice]="登録に成功しました"
      redirect_to admin_genres_path(@genre)
    else
      @genres = Genre.all
      flash.now[:notice]="登録に失敗しました"
      render "index"
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    if genre.update(genre_params)
      flash[:notice]="編集に成功しました"
      redirect_to admin_genres_path(@genre)
    else
      @genres = Genre.all
      flash.now[:notice]="編集に失敗しました"
      render "index"
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.page(params[:page]).reverse_order.per(12)

  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.page(params[:page]).per(5)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice]="新しい商品を登録しました"
      redirect_to admin_item_path(@item.id)
    else
      flash.now[:notice]="各項目に情報を入力してください"
      render "new"
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice]="商品情報を更新しました"
      redirect_to admin_item_path(@item.id)
    else
      flash.now[:notice]="各項目に情報を入力してください"
      render "edit"
    end
  end

  private
  def item_params
    params.require(:item).permit(:genre_id,:name,:image,:introduction,:price,:is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if current_admin
      flash[:notice] = "管理者ログインに成功しました"
      admin_path
    else
      flash[:notice] = "会員ログインに成功しました"
      root_path
    end
  end

  def after_sign_out_path_for(resource)
    if resource == :customer
      flash[:notice] = "会員ログアウトに成功しました"
      root_path
    else
      flash[:notice] = "管理者ログアウトに成功しました"
      new_admin_session_path
    end
  end

  def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/4bdd89c768.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm pb-2">
      <nav class="navbar navbar-expand-lg p-0 mt-4 mb-4">
        <div class="container">
          <div>
          <%= link_to root_path, class: "logo" do %>
            <%= image_tag "linkedin_banner_image_1.png", size: "200x80" %>
          <% end %>
          </div>
          <div class="col-md-3 text-right">
            <% if customer_signed_in? %>
            <p>ようこそ、<%= current_customer.last_name %>さん！</p>
            <% end %>
          </div>

          <div class="col-md-7">
            <div class="float-right">
              <ul class="navbar-nav">
                <% if customer_signed_in? %>
                   <li class="nav-item">
                    <%= link_to "マイページ", customers_my_page_path, class: "nav-link btn border px-3 mr-3" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "商品一覧", items_path, class: "nav-link btn border px-3 mr-3" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "カート", cart_items_path, class: "nav-link btn border px-3 mr-3" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "nav-link btn border px-3" %>
                  </li>
                <% elsif admin_signed_in? %>
                  <li class="nav-item">
                    <%= link_to "商品一覧", admin_items_path, class: "nav-link btn border px-3 mr-2" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "会員一覧", admin_customers_path, class: "nav-link btn border px-3 mr-2" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "注文履歴一覧", admin_path, class: "nav-link btn border px-3 mr-2" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "ジャンル一覧", admin_genres_path, class: "nav-link btn border px-3 mr-2" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link btn border px-3" %>
                  </li>
                <% else%>
                  <li class="nav-item">
                    <%= link_to "About", about_path, class: "nav-link btn border px-3 mr-3"%>
                  </li>
                  <li class="nav-item">
                    <%= link_to "商品一覧", items_path, class: "nav-link btn border px-3 mr-3" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "新規登録", new_customer_registration_path, class: "nav-link btn border px-3 mr-3" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "ログイン", new_customer_session_path, class: "nav-link btn border px-3" %>
                  </li>
                <% end %>
              </ul>
            </div>

            <div class="float-right mt-2">
            <%#= form_tag admin_genres_path, method: :get do %>
              <%= text_field_tag :serch, params[:serch] %>
              <%= submit_tag "Serch", :name => nil %>
            <%# end %>
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <div class="mt-5"></div>
        <p id="notice"><%= flash[:notice] %></p>
        <p id="error"><%= flash[:error] %></p>
        <%= yield %>
    </main>

    <footer>
    </footer>
  </body>
</html>